### ISSUE TITLE
Error: too many sweep line segments

### ISSUE THREAD

**Issue by tafflin** [BlinkTagInc/gtfs-to-geojson#18]
I get "Error: Infinite loop when passing sweep line over endpoints (too many sweep line segments). Please file a bug report." message when trying to run stops-dissolved generation with buffer size >500 meters.
My config:
{
  "agencies": [
    {
      "agency_key": "allstops",
      "path": "/home/tafflin/Documents/gtfs-to-geojson/GTFS_NI.zip",
      "exclude": [ 
        "stop_times",
        "trips",
        "shapes"
      ]
    }
  ],
  "bufferSizeMeters": 800,
  "coordinatePrecision": 5,
  "outputType": "agency",
  "outputFormat": "stops-dissolved",
  "zipOutput": false
}
[GTFS_NI.zip](https://github.com/BlinkTagInc/gtfs-to-geojson/files/9533504/GTFS_NI.zip)

**Comment by brendannee** [comment]
That sounds like an issue with the `polygon-clipping` library in use.

For such a large amount of stops, I suggest trying to just generate geojson of the stops, then importing that geojson into QGIS and manually creating the buffer there.

**Comment by tafflin** [comment]
I checked the issue once again with a newer version you updated recently and I still get this message with buffersize of 800 meters for the same GTFS file.
However I don't have any issues generating a geojson with 400 m buffer from the same file.

**Comment by brendannee** [comment]
I just tried it with the zipfile linked above and the config with the latest GTFS-to-Geojson and it did work (it took a while 1592 seconds).
(see attached geojson file saved as .txt as GitHub comments do not allow .geojson file uploads)
[NI.txt](https://github.com/BlinkTagInc/gtfs-to-geojson/files/9613123/NI.txt)
