### ISSUE TITLE
Wrong attribute order in "feature"

### ISSUE THREAD

**Issue by GuiChevis** [BlinkTagInc/gtfs-to-geojson#29]
I noticed some geojson decoders (specifically [MKGeoJSONDecoder](https://developer.apple.com/documentation/mapkit/mkgeojsondecoder) in Swift) require a specific attribute in order to work, and the result I am getting with your code gives me a different order. 

The problem I am facing right now is with the order of the attributes "properties" and "geometry" in the ["feature"](https://datatracker.ietf.org/doc/html/rfc7946#section-3.2) object. This decoder expects "geometry" first, but the code generates it reversed.

**Comment by GuiChevis** [comment]
Here is my config.json file

```
{
  "agencies": [
    {
      "agency_key": "SPTRANS",
      "url": "https://www.sptrans.com.br/umbraco/Surface/PerfilDesenvolvedor/BaixarGTFS"
    }
  ],
  "bufferSizeMeters": 400,
  "coordinatePrecision": 5,
  "outputType": "agency",
  "outputFormat": "lines-and-stops",
  "startDate": "20240301",
  "endDate": "20240331",
  "verbose": true,
  "zipOutput": false
}
```

**Comment by brendannee** [comment]
Hi - did you figure out a workaround for this issue?

**Comment by GuiChevis** [comment]
Hey, thanks for the response, I figured it wasn't actually the order that was messing things up in my code!
