### ISSUE TITLE
No MultiLineString support

### ISSUE THREAD

**Issue by GuiChevis** [BlinkTagInc/gtfs-to-geojson#30]
All lines I get in the geojson file are "LineString", some parsers and libraries like MKGeoJSON from MapKit in Swift can render multiple lines ([MultiLineString](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.5)) at once if the geojson contains this type of feature.

**Comment by brendannee** [comment]
Great idea.

I updated the library so when you export "lines" or "lines-and-stops" is uses MultiLineString for each route line. Check out this release and let me know what you think. https://github.com/BlinkTagInc/gtfs-to-geojson/releases/tag/3.7.6

**Comment by GuiChevis** [comment]
Thank you for the quick response! I don't know if I am doing something wrong, but I am not getting MultiLineStrings with the following config:

```
{
  "agencies": [
    {
      "agency_key": "SPTRANS",
      "url": "https://www.sptrans.com.br/umbraco/Surface/PerfilDesenvolvedor/BaixarGTFS"
    }
  ],
  "bufferSizeMeters": 400,
  "coordinatePrecision": 6,
  "outputType": "agency",
  "outputFormat": "lines-and-stops",
  "startDate": "20240301",
  "endDate": "20240331",
  "verbose": true,
  "zipOutput": false
}
```

**Comment by brendannee** [comment]
Make sure you update your version of gtfs-to-GeoJSON to the latest version 3.7.6

**Comment by GuiChevis** [comment]
Thank you, got it to work!
