### ISSUE TITLE
Shapes.txt doesn't seem to be used

### ISSUE THREAD

**Issue by 2803media** [BlinkTagInc/gtfs-to-geojson#9]
I use this tool to build missing shapes.txt from some GTFS : https://github.com/pailakka/gtfs-shape-router

the file created is here: https://gist.github.com/2803media/817034ceca0d3f3a14924c5c51d9377e

I use the gtfs here: http://transitfeeds.com/p/metropole-europeenne-de-lille/1202/latest/download

I copy the missing shapes.txt inside the unzip folder

But it seems that gtfs-to-geojson doesn't use the shapes.txt, do I miss something?

The result in QGIS:

![Capture d’écran 2020-11-11 à 14 27 34](https://user-images.githubusercontent.com/642545/98817211-138a7700-242a-11eb-8643-a0e487edabed.jpg)

When I load the shapes.txt in QGIS the file seem good as you can see below:

![Capture d’écran 2020-11-11 à 14 30 47](https://user-images.githubusercontent.com/642545/98817540-84319380-242a-11eb-8bc8-6fbab18b8a26.jpg)

The geojson of the shapes.txt build with the tool to create the missing file seem also good:

![Capture d’écran 2020-11-11 à 14 33 31](https://user-images.githubusercontent.com/642545/98817752-e4283a00-242a-11eb-8089-5d0a34b473d1.jpg)

Thanks!

**Comment by brendannee** [comment]
Each trip in trips.txt needs to have a shape_id in order to be matched with the correct shape file. http://gtfs.org/reference/static/#tripstxt

**Comment by 2803media** [comment]
It's for that;)

Thanks for your kind reply!

**Comment by 2803media** [comment]
The tool create a trips_shape.txt file, I just rename it and get the shapes in the geojson!

![Capture d’écran 2020-11-11 à 22 34 09](https://user-images.githubusercontent.com/642545/98866989-1a3add80-246e-11eb-811e-c69e9282fb2b.jpg)
